### ISSUE TITLE
ReqAnalyzer regression test issues

### ISSUE THREAD

**Issue by henkele** [ultimate-pa/ultimate#534]
Failing tests (18.11.2020)

- [ ] rtinconsistency_test5.req (see #500, #495)
- [ ] rtinconsistency_test36.req (see #493)
- [ ] rtinconsistency_test118.req

- [x] rtinconsistency_test2.req (timeout, fixed by 62386e1c2b885f279a9c37d1cf400b1e763cef54)
- [x] rtinconsistency_test34.req (timeout, fixed by 62386e1c2b885f279a9c37d1cf400b1e763cef54)
- [x] rtinconsistency_test112.req (timeout, fixed by 62386e1c2b885f279a9c37d1cf400b1e763cef54)
- [x] rtinconsistency_test29.req (phaseE-problem, same as #494, solved by aa81852db9ec0e4d689b025a1ba17d1a5bdfaa57)
- [x] rtinconsistency_test40.req (see #494, solved by aa81852db9ec0e4d689b025a1ba17d1a5bdfaa57)
- [x] vacuity_test0.req (see #538, #541)
- [x] vacuity_test2.req (see #538, #541)
- [x] vacuity_test8.req (see #538, #541)
- [x] vacuity_test10.req (see #538,#541)
- [x] vacuity_test16.req (see #538, #541)
- [x] vacuity_test18.req (see #538, #541)
- [x] vacuity_test26.req (see #538, #541)
- [x] vacuity_test32.req (see #538, #541)
- [x] vacuity_test34.req (see #538, #541)
- [x] vacuity_test42.req (see #506, solved by a415d3de7a11fbf759820e73a2cffaa7fcb05444)
- [x] vacuity_test53.req (see #539, #541)
- [x] vacuity_test64.req (see #539, #541)
- [x] vacuity_test75.req (see #539, #541)
- [x] vacuity_test86.req (see #539, #541)
